# 토큰화

 모델이 다룰 수 있는 기본 단위 ➔ Token 
 문장, 어절, 형태소
- 서브워드 : 자주 붙어있는 글자끼리를 서브워드로 생각함 ➔ 사전에는 없을 수도, 뜻이 있을 수도 없을 수도 
ex) 위는 : 
- 영어는 어절 , 한국어는 형태소단위로 많이 쪼갬
- 딥러닝, llm, 생성 쪽은 서브워드 방식
---

## 단어 기반 토큰화 (word - level - tokenization)
- 어절 ( 공백 ) 또는 형태소 단위로 단어를 나눔 
- 한국어의 경우 단어 + 어미/조사 결합 ➔  어절 단위로 쪼개면 단어의 크기가 기하급수적으로 생겨버림.
- 학교에, 학교가, 학교를, 학교는, .... 
- 빈도수가 높은 토큰화(유니크)를 모아둠 ➔ 어휘사전(단어사전)을 만듦. 이 경우 단어 기반 토큰화의 경우 어휘사전이 기하급수적으로 커짐 
---
- 이해가 중심일 때는 조사 제거 
- 생성이 포함될 때는 조사 포함 
---
**미등록 어휘(OOV : OUT OF VOCA)** <br>
어휘 사전을 바탕으로 새로운 문서가 들어왔을 때 어휘사전을 기반으로 분리 ➔ 즉 같은 의미인 단어들이 중복 등록. <br>
메모리 낭비, 학습효율성 저하 <br>
➔ 그래서 한국어는 형태소 단위 토큰화가 필요 <br>
*형태소 : 뜻을 가진 가장 작은 말의 단위*

## 서브워브(SUBWORD LEVEL) 기반 토큰화 - BPE, Wordpiece, unigram
* 트랜스포머 기반 모델(bert, gpt, 라마)에서 표준으로 사용함.
* 단어를 기준으로 토큰x, 문자와 단어의 중간 수준 ➔ 서브워드로 토큰화
* 동작원리 : 
    * 자주 등장하는 문자열 조합 ( 빈도가 낮거나 희귀) ➔ 여러 서브워드로 분할 ➔ 하나의 토큰으로
    * 빈도가 높은단어 ➔ 하나의 토큰
* 장점: 
    * 글자 단위로 붙임 ➔ oov가 나오지 않음. 밥을 ➔ 밥, 을, 밥을 ➔ oov가 나오지 않도록 정의함
    * 어휘 사전 크기 최적화
    * 형태론적 의미 포착 ➔ 접두사 접미사 등. ➔ 문법적으로 이해할 수 있는 방식

---

**의미** <br>
사람이 이해하는 의미 / 컴퓨터가 이해하는 방식의 의미 (그냥 자주 등장하면 글자들의 조합을 의미로 파악함) <br>

## 한국어 형태소 분석기
- kiwipiepy
- konlpy

### kiwipiepy (korean intelligent word identifier)
- 최근에 많이 사용되는 한국어 토크나이저.
- 체언(명사, 대명사): `N`, 용언(동사, 형용사): `V`<br> 수식언(관형사, 부사): `M`,  관계언(조사):`J`, 어미: `E`, 기호: `S`
---
**Kiwi 클래스 사용** <br>
- 키위 - 자체의 어휘사전을 만들어둠. ( 토큰화할 때 사용할 각각의 단어들을 정의해둠)
- 주요 메소드
    - `tokenize(text)` : 형태소 분석 기반 토큰화 수행 
    - `analyse(text)`: 토크나이즈 보다 좀 더 상세한 분석 진행 & 여러 분석 결과 조회가능 
    - `add_user_word(word, pos, score)`: 사전에 직접 단어 등록
    - `space(text)` : 띄어쓰기 교정

In [7]:
import kiwipiepy
from kiwipiepy import Kiwi
from pprint import pprint

kiwipiepy.__version__

'0.23.1'

In [9]:
kiwi = Kiwi()

In [10]:
# 형태소 기반 토큰화 - tokenize()

txt = "나는 자연어 처리를 공부합니다. \n 자연어 처리란 무엇일까요?"
tokens = kiwi.tokenize(txt)

print(tokens)

[Token(form='나', tag='NP', start=0, len=1), Token(form='는', tag='JX', start=1, len=1), Token(form='자연어 처리', tag='NNP', start=3, len=6), Token(form='를', tag='JKO', start=9, len=1), Token(form='공부', tag='NNG', start=11, len=2), Token(form='하', tag='XSV', start=13, len=1), Token(form='ᆸ니다', tag='EF', start=13, len=3), Token(form='.', tag='SF', start=16, len=1), Token(form='자연어 처리', tag='NNP', start=20, len=6), Token(form='란', tag='JX', start=26, len=1), Token(form='무엇', tag='NP', start=28, len=2), Token(form='이', tag='VCP', start=30, len=1), Token(form='ᆯ까요', tag='EF', start=30, len=3), Token(form='?', tag='SF', start=33, len=1)]

지금 토큰이라는 객체에 담겨져서 나옴 ➔ token이라는 클래스를 만들어서 묶어서
즉 하나의 값이 여러개의 값으로 구성된 경우 ➔ 자료구조 방법, 클래스를 이용해서 객체로 ➔ 객체로 담겨져서 온다면 값이 여러개존재한다는 거고, 각 객체에 대한 메서드가 존재한다는 것 <br>
Token 객체에 담겨서 리스트로 반환
- form : 단어 정보
- tag : 품사 정보
- start : 시작 인덱스
- len : 글자수 .?

In [24]:
# Token 객체에서 속성값들 조회

for token in tokens:
    # print(token)
    # token = Token
    result = (f"토큰문자열: {token.form} |"
              f"토큰 원형 : {token.lemma} |"
              f"토큰 품사: {token.tag} |"
              f"문서 내 시작 위치: {token.start} |"
              f"토큰 글자수: {token.len}"
              f"토큰이 있는 행번호 : {token.line_number} |"
              f"토큰이 몇번째 문장에 있는지 : {token.sent_position} |"
              f"토큰이 몇번째 어절인지 : {token.word_position}")
    
    print(result)
    print("-------------------------------------")

# 몇번째 어절이라는 건 ➔ 문장 내에서 몇번째 어절인가임. ! 


import pandas as pd

def tokentodf(tokens):
    """
    Token 객체 리스트를 받아 가독성이 좋은 Pandas DataFrame으로 변환합니다.
    """
    # 1. 각 토큰의 속성들을 딕셔너리 형태로 리스트에 담기
    data = []
    for token in tokens:
        token_info = {
            "토큰문자열": token.form,
            "토큰 원형": token.lemma,
            "토큰 품사": token.tag,
            "문서 내 시작 위치": token.start,
            "토큰 글자수": token.len,
            "행번호": token.line_number,
            "문장 번호": token.sent_position,
            "문장 내 어절 위치": token.word_position
        }
        data.append(token_info)
    
    # 2. 데이터프레임 생성 및 반환
    df = pd.DataFrame(data)
    return df

토큰문자열: 나 |토큰 원형 : 나 |토큰 품사: NP |문서 내 시작 위치: 0 |토큰 글자수: 1토큰이 있는 행번호 : 0 |토큰이 몇번째 문장에 있는지 : 0 |토큰이 몇번째 어절인지 : 0
-------------------------------------
토큰문자열: 는 |토큰 원형 : 는 |토큰 품사: JX |문서 내 시작 위치: 1 |토큰 글자수: 1토큰이 있는 행번호 : 0 |토큰이 몇번째 문장에 있는지 : 0 |토큰이 몇번째 어절인지 : 0
-------------------------------------
토큰문자열: 자연어 처리 |토큰 원형 : 자연어 처리 |토큰 품사: NNP |문서 내 시작 위치: 3 |토큰 글자수: 6토큰이 있는 행번호 : 0 |토큰이 몇번째 문장에 있는지 : 0 |토큰이 몇번째 어절인지 : 1
-------------------------------------
토큰문자열: 를 |토큰 원형 : 를 |토큰 품사: JKO |문서 내 시작 위치: 9 |토큰 글자수: 1토큰이 있는 행번호 : 0 |토큰이 몇번째 문장에 있는지 : 0 |토큰이 몇번째 어절인지 : 2
-------------------------------------
토큰문자열: 공부 |토큰 원형 : 공부 |토큰 품사: NNG |문서 내 시작 위치: 11 |토큰 글자수: 2토큰이 있는 행번호 : 0 |토큰이 몇번째 문장에 있는지 : 0 |토큰이 몇번째 어절인지 : 3
-------------------------------------
토큰문자열: 하 |토큰 원형 : 하 |토큰 품사: XSV |문서 내 시작 위치: 13 |토큰 글자수: 1토큰이 있는 행번호 : 0 |토큰이 몇번째 문장에 있는지 : 0 |토큰이 몇번째 어절인지 : 3
-------------------------------------
토큰문자열: ᆸ니다 |토큰 원형 : ᆸ니다 |토큰 품사: EF |문서 내 시작 위치: 13 |토큰 글자수: 3토큰이 있는 행번호 : 0 |토큰이 몇번째 문장에 있는지 : 0 |토큰이 몇번째 어절인지 : 3
-------------------------------------
토큰문자열: . |토큰 원형 : . |토큰 품사: SF |문서 내 시작 위치: 16 |토큰 글자수: 1토큰이 있는 행번호 : 0 |토큰이 몇번째 문장에 있는지 : 0 |토큰이 몇번째 어절인지 : 3
-------------------------------------
토큰문자열: 자연어 처리 |토큰 원형 : 자연어 처리 |토큰 품사: NNP |문서 내 시작 위치: 20 |토큰 글자수: 6토큰이 있는 행번호 : 1 |토큰이 몇번째 문장에 있는지 : 1 |토큰이 몇번째 어절인지 : 0
-------------------------------------
토큰문자열: 란 |토큰 원형 : 란 |토큰 품사: JX |문서 내 시작 위치: 26 |토큰 글자수: 1토큰이 있는 행번호 : 1 |토큰이 몇번째 문장에 있는지 : 1 |토큰이 몇번째 어절인지 : 1
-------------------------------------
토큰문자열: 무엇 |토큰 원형 : 무엇 |토큰 품사: NP |문서 내 시작 위치: 28 |토큰 글자수: 2토큰이 있는 행번호 : 1 |토큰이 몇번째 문장에 있는지 : 1 |토큰이 몇번째 어절인지 : 2
-------------------------------------
토큰문자열: 이 |토큰 원형 : 이다 |토큰 품사: VCP |문서 내 시작 위치: 30 |토큰 글자수: 1토큰이 있는 행번호 : 1 |토큰이 몇번째 문장에 있는지 : 1 |토큰이 몇번째 어절인지 : 2
-------------------------------------
토큰문자열: ᆯ까요 |토큰 원형 : ᆯ까요 |토큰 품사: EF |문서 내 시작 위치: 30 |토큰 글자수: 3토큰이 있는 행번호 : 1 |토큰이 몇번째 문장에 있는지 : 1 |토큰이 몇번째 어절인지 : 2
-------------------------------------
토큰문자열: ? |토큰 원형 : ? |토큰 품사: SF |문서 내 시작 위치: 33 |토큰 글자수: 1토큰이 있는 행번호 : 1 |토큰이 몇번째 문장에 있는지 : 1 |토큰이 몇번째 어절인지 : 2
-------------------------------------

보통은 form 보다는 lemma( 원형 )으로 뽑아서 좀 더 중복을 제거하기 위해 사용함.

In [26]:
txt_list = [txt, "자연어처리는 nlp라고 합니다. 자연어 처리는 Transformer모델이 성능이 더 좋아요."]

print(txt_list)

tokens_iterable = kiwi.tokenize(txt_list)
tokens_iterable

['나는 자연어 처리를 공부합니다. \n 자연어 처리란 무엇일까요?', '자연어처리는 nlp라고 합니다. 자연어 처리는 Transformer모델이 성능이 더 좋아요.']

In [ ]:
for token_list in tokens_iterable:

In [32]:
txt_list = [txt, "자연어처리는 nlp라고 합니다. 자연어 처리는 Transformer모델이 성능이 더 좋아요."]

# 리스트 컴프리헨션으로 한 번에 데이터프레임 리스트 생성
dfs = [tokentodf(token_list) for token_list in kiwi.tokenize(txt_list)]

dfs[0]

     토큰문자열   토큰 원형 토큰 품사  문서 내 시작 위치  토큰 글자수  행번호  문장 번호  문장 내 어절 위치
0        나       나    NP           0       1    0      0           0
1        는       는    JX           1       1    0      0           0
2   자연어 처리  자연어 처리   NNP           3       6    0      0           1
3        를       를   JKO           9       1    0      0           2
4       공부      공부   NNG          11       2    0      0           3
5        하       하   XSV          13       1    0      0           3
6      ᆸ니다     ᆸ니다    EF          13       3    0      0           3
7        .       .    SF          16       1    0      0           3
8   자연어 처리  자연어 처리   NNP          20       6    1      1           0
9        란       란    JX          26       1    1      1           1
10      무엇      무엇    NP          28       2    1      1           2
11       이      이다   VCP          30       1    1      1           2
12     ᆯ까요     ᆯ까요    EF          30       3    1      1           2
13       ?       ?    SF          33       1    1      1           2

In [33]:
dfs[1]

          토큰문자열        토큰 원형 토큰 품사  문서 내 시작 위치  토큰 글자수  행번호  문장 번호  문장 내 어절 위치
0        자연어 처리       자연어 처리   NNP           0       5    0      0           0
1             는            는    JX           5       1    0      0           0
2           nlp          nlp    SL           7       3    0      0           1
3             이           이다   VCP          10       0    0      0           1
4            라고           라고    EC          10       2    0      0           1
5             하           하다    VV          13       1    0      0           2
6           ᆸ니다          ᆸ니다    EF          13       3    0      0           2
7             .            .    SF          16       1    0      0           2
8        자연어 처리       자연어 처리   NNP          18       6    0      1           0
9             는            는    JX          24       1    0      1           1
10  Transformer  Transformer    SL          26      11    0      1           2
11           모델           모델   NNG          37       2    0      1           2
12            이            이   JKS          39       1    0      1           2
13           성능           성능   NNG          41       2    0      1           3
14            이            이   JKS          43       1    0      1           3
15            더            더   MAG          45       1    0      1           4
16            좋           좋다    VA          47       1    0      1           5
17           어요           어요    EF          48       2    0      1           5
18            .            .    SF          50       1    0      1           5

In [35]:
result = kiwi.analyze(txt, top_n=3)

result

[([Token(form='나', tag='NP', start=0, len=1),
   Token(form='는', tag='JX', start=1, len=1),
   Token(form='자연어 처리', tag='NNP', start=3, len=6),
   Token(form='를', tag='JKO', start=9, len=1),
   Token(form='공부', tag='NNG', start=11, len=2),
   Token(form='하', tag='XSV', start=13, len=1),
   Token(form='ᆸ니다', tag='EF', start=13, len=3),
   Token(form='.', tag='SF', start=16, len=1),
   Token(form='자연어 처리', tag='NNP', start=20, len=6),
   Token(form='란', tag='JX', start=26, len=1),
   Token(form='무엇', tag='NP', start=28, len=2),
   Token(form='이', tag='VCP', start=30, len=1),
   Token(form='ᆯ까요', tag='EF', start=30, len=3),
   Token(form='?', tag='SF', start=33, len=1)],
  -64.59104919433594),
 ([Token(form='나', tag='NP', start=0, len=1),
   Token(form='는', tag='JX', start=1, len=1),
   Token(form='자연어', tag='NNP', start=3, len=3),
   Token(form='처리', tag='NNG', start=7, len=2),
   Token(form='를', tag='JKO', start=9, len=1),
   Token(form='공부', tag='NNG', start=11, len=2),
   Token(form='하', tag='XSV', start=13, len=1),
   Token(form='ᆸ니다', tag='EF', start=13, len=3),
   Token(form='.', tag='SF', start=16, len=1),
   Token(form='자연어', tag='NNP', start=20, len=3),
   Token(form='처리', tag='NNG', start=24, len=2),
   Token(form='란', tag='JX', start=26, len=1),
   Token(form='무엇', tag='NP', start=28, len=2),
   Token(form='이', tag='VCP', start=30, len=1),
   Token(form='ᆯ까요', tag='EF', start=30, len=3),
   Token(form='?', tag='SF', start=33, len=1)],
  -74.18604278564453),
 ([Token(form='나', tag='NP', start=0, len=1),
   Token(form='는', tag='JX', start=1, len=1),
   Token(form='자연어 처리', tag='NNP', start=3, len=6),
   Token(form='를', tag='JKO', start=9, len=1),
   Token(form='공부', tag='NNG', start=11, len=2),
   Token(form='하', tag='VV', start=13, len=1),
   Token(form='ᆸ니다', tag='EF', start=13, len=3),
   Token(form='.', tag='SF', start=16, len=1),
   Token(form='자연어 처리', tag='NNP', start=20, len=6),
   Token(form='이', tag='VCP', start=26, len=0),
   Token(form='란', tag='ETM', start=26, len=1),
   Token(form='무엇', tag='NP', start=28, len=2),
   Token(form='이', tag='VCP', start=30, len=1),
   Token(form='ᆯ까요', tag='EF', start=30, len=3),
   Token(form='?', tag='SF', start=33, len=1)],
  -77.83578491210938)]

float 이 의미하는 바가 무엇인가. ➔ 0에 가까울 수록 점수가 높은 것. ➔ 걍 좋은 것 <br>
토큰별로 점수가 등록되어 있는 게 있는데 ➔ 어떻게 토큰화하는 게 가장 적절할지 맞춰서 ➔ best로 뽑아주는 게 1번째 <br>
여러 분리 방법을 다 보여줌. <br>
좀 더 자세한 분석 결과를 볼

In [36]:
# 띄어쓰기 사용하기

txt ="나는자연어처리를공부합니다자연어처리란무엇일까요"
result = kiwi.space(txt)
result

'나는 자연어 처리를 공부합니다 자연어 처리란 무엇일까요'

In [37]:
txt_list = [txt, "아버지가방에들어가신다"]
result_list = kiwi.space(txt_list)

for i in result_list:
    print(i)

나는 자연어 처리를 공부합니다 자연어 처리란 무엇일까요
아버지가 방에 들어가신다

In [39]:
# 문서를 문장단위로 분리. slit_into_sents
doc = '폴 바버 브라이튼 CEO는 영국 매체 <토크스포츠>와 인터뷰에서 토트넘의 제안을두번이나 거절했다고 전했다. 또한 바버 CEO는 판 헤케의 계약기간이1년밖에남지 않았으나 쉽게 타 팀으로 내줄생각이 없다는점도 분명히 했다. 바버 CEO는 "최고 수준 선수들에게 관심이 쏠리는 건 당연하고, 판 헤케 역시 마찬가지"라고 운을 뗀 후, "판 헤케를 향한 관심은 오래전부터 이어져 왔고 여러 구단에서 접근하고 있다"라고 시장에서 판 헤케가 많은 인기를 끌고 있다는 점은인정했다.'

In [40]:
sent_list = kiwi.split_into_sents(doc)

sent_list

[Sentence(text='폴 바버 브라이튼 CEO는 영국 매체 <토크스포츠>와 인터뷰에서 토트넘의 제안을두번이나 거절했다고 전했다.', start=0, end=59, tokens=None, subs=[]),
 Sentence(text='또한 바버 CEO는 판 헤케의 계약기간이1년밖에남지 않았으나 쉽게 타 팀으로 내줄생각이 없다는점도 분명히 했다.', start=60, end=122, tokens=None, subs=[]),
 Sentence(text='바버 CEO는 "최고 수준 선수들에게 관심이 쏠리는 건 당연하고, 판 헤케 역시 마찬가지"라고 운을 뗀 후, "판 헤케를 향한 관심은 오래전부터 이어져 왔고 여러 구단에서 접근하고 있다"라고 시장에서 판 헤케가 많은 인기를 끌고 있다는 점은인정했다.', start=123, end=262, tokens=None, subs=[Sentence(text='판 헤케를 향한 관심은 오래전부터 이어져 왔고 여러 구단에서 접근하고 있다', start=185, end=226, tokens=None, subs=None)])]

In [ ]:
# 글자만 가져오기
for sent in sent_list:
    # print(sent.text)
    print(kiwi.space(sent.text)) # 띄어쓰기 오류 바로잡기 
    print("-------------------------------------")

폴 바버 브라이튼 CEO는 영국 매체 <토크스포츠>와 인터뷰에서 토트넘의 제안을두번이나 거절했다고 전했다.
또한 바버 CEO는 판 헤케의 계약기간이1년밖에남지 않았으나 쉽게 타 팀으로 내줄생각이 없다는점도 분명히 했다.
바버 CEO는 "최고 수준 선수들에게 관심이 쏠리는 건 당연하고, 판 헤케 역시 마찬가지"라고 운을 뗀 후, "판 헤케를 향한 관심은 오래전부터 이어져 왔고 여러 구단에서 접근하고 있다"라고 시장에서 판 헤케가 많은 인기를 끌고 있다는 점은인정했다.